// Deploy MediaRegistry to Ritual Chain (1979).
import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPublicClient, createWalletClient, http, formatEther } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { ritualChain, DEFAULT_MODEL_ID } from './lib.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const artifact = JSON.parse(fs.readFileSync(path.join(root, 'out', 'MediaRegistry.json'), 'utf8'));

// Initial threshold (scaled by 1e6). Tunable later via setThreshold().
const INITIAL_THRESHOLD = 2_500_000n;

const account = privateKeyToAccount(process.env.PRIVATE_KEY);
const publicClient = createPublicClient({ chain: ritualChain, transport: http() });
const walletClient = createWalletClient({ account, chain: ritualChain, transport: http() });

console.log('Deployer:', account.address);
console.log('Balance :', formatEther(await publicClient.getBalance({ address: account.address })), 'RITUAL');
console.log('Model   :', DEFAULT_MODEL_ID);
console.log('Deploying MediaRegistry...');

const hash = await walletClient.deployContract({
  abi: artifact.abi,
  bytecode: artifact.bytecode,
  args: [DEFAULT_MODEL_ID, INITIAL_THRESHOLD],
});
console.log('Deploy tx:', hash);

const receipt = await publicClient.waitForTransactionReceipt({ hash });
console.log('Status   :', receipt.status);
console.log('Contract :', receipt.contractAddress);
console.log('Explorer :', `https://explorer.ritualfoundation.org/address/${receipt.contractAddress}`);

// Persist the address into .env and frontend/config.js
const envPath = path.join(root, '.env');
let env = fs.readFileSync(envPath, 'utf8');
env = env.replace(/MEDIA_REGISTRY_ADDRESS=.*/g, `MEDIA_REGISTRY_ADDRESS=${receipt.contractAddress}`);
fs.writeFileSync(envPath, env);

fs.writeFileSync(
  path.join(root, 'frontend', 'config.js'),
  `// auto-generated by deploy.mjs\nexport const CONTRACT_ADDRESS = '${receipt.contractAddress}';\nexport const RPC_URL = '${process.env.RITUAL_RPC_URL}';\nexport const EXPLORER = 'https://explorer.ritualfoundation.org';\n`
);
console.log('Wrote address to .env and frontend/config.js');
