// auto-generated by deploy.mjs
export const CONTRACT_ADDRESS = '0x1da9fb28c6f3b43f4d4487e833873cf2856b809a';
export const RPC_URL = 'https://rpc.ritualfoundation.org';
export const EXPLORER = 'https://explorer.ritualfoundation.org';
